name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
  release:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - arm_arm1176jzf-s_vfp
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a7_vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_neon
          - arm_cortex-a9_vfpv3-d16
          - i386_pentium4
          - i386_pentium-mmx
          - mips_24kc
          - mips_4kec
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - mips_mips32
          - x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare package
        run: |
          sed -i '/^SRCDIR/ s/$/\/feed/' openwrt/Makefile
          mkdir -p feed/scutclient
          mv openwrt/Makefile feed/scutclient/
          cat feed/scutclient/Makefile

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          NO_DEFAULT_FEEDS: 1
          PACKAGES: scutclient

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-packages
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
